set_property IOSTANDARD LVCMOS33 [get_ports in1]
set_property IOSTANDARD LVCMOS33 [get_ports in2]
set_property IOSTANDARD LVCMOS33 [get_ports out]
set_property PACKAGE_PIN P5 [get_ports in1]
set_property PACKAGE_PIN P4 [get_ports in2]
set_property PACKAGE_PIN G4 [get_ports out]
